### PR TITLE
added ability to invalidate current token, which will force new token…

### PR DESCRIPTION
**Pull request by nathan-boyd**
Added ability to forcibly invalidate the client's access token.

### CODE REVIEW

**Comment by dougwilson** [comment]
Hi @nathan-boyd , looks like the tests are failing. Please take a look :)

**Comment by nathan-boyd** [comment]
fixed

**Comment by dougwilson** [comment]
Thanks! @vernak2539 , thoughts on this change? We are working to fix an issue we have discovered in our production application with bad token lifecycle handling, specifically in the REST SDK:

1. A request is made and this module return an access token it does not think is expired
2. The response is a 401 with invalid token
3. The REST SDK then does a second request
4. This module will still think that access token is not expired and return it again
5. The response is a 401 with invalid token

The idea here is to provide an API in the Auth SDK for modules like REST and SOAP to signal that a it determined a specific access token is now invalid, so the next call to the library will fetch a new access token (if it has not already done so).

**Comment by dougwilson** [comment]
Also, @nathan-boyd , please add some documentation to the README in this PR.

**Comment by dougwilson** [comment]
Nevermind, the docs on in the wiki.

**Comment by vernak2539** [comment]
@dougwilson @nathan-boyd it makes sense to me. I guess the only question is, why have this method when you [can force](https://github.com/salesforce-marketingcloud/FuelSDK-Node-Auth/wiki/getAccessToken) the client to get a new token? I see that [I did mess up](https://github.com/salesforce-marketingcloud/FuelSDK-Node-REST/blob/master/lib/fuel-rest.js#L108) and not force the auth client to go back to the API. Maybe that would be an easier solution than this?

I'm fine either way, I'll probably end up updating the REST client anyways if you guys want to proceed with this way

**Comment by dougwilson** [comment]
Hey @vernak2539 , just following up here after our phone chat. I believe we are on the same page with the purpose of this change, which is intended to make the whole process slightly more efficient, even though a force would technically work.

**Comment by vernak2539** [comment]
Yep, cheers!

**Pull request merged**
